import openai

def details(query):

    if 'highest performing ads' in query:
        model_response = '''
        The highest performing ad for Loreal-Singapore is titled 'Adname1'.

        | ad_name             | impressions | ctr   | cpc  |
        | ------------------  | ----------- | ----- | ---- |
        | Adname1-1-23-2023   | 265,217     | 1.3%  | $1.78 |
        | Adname2-2-19-2023   | 215,823     | 1.9%  | $1.15 |
        | Adname3-1-13-2023   | 182,349     | 2.4%  | $0.91 |
        | Adname4-4-07-2023   | 105,421     | 0.9%  | $2.43 |
        | Adname5-2-14-2023   | 68,127      | 1.1%  | $2.05 |
        '''
    
    elif 'attribute' in query:
        model_response = '''
        The attributes of the 'A' ad with the highest confidence are Eyelash, Lips, and Skin. 

        - Eyelash (88% confidence)
        - Lips (69% confidence)
        - Skin (37% confidence)

        These attributes are generated by an artificial intelligence model that analyzes the visual elements of the ad, such as colors, patterns, and objects, and identifies the most prominent ones with a certain level of confidence.
        '''

    elif 'lowest performing ads' in query:
        model_response = '''
        The lowest performing ad for Loreal-Singapore is 'A'.

        | ad_name             | impressions | ctr   | cpc  |
        | ------------------  | ----------- | ----- | ---- |
        | Adname5-4-25-2023   | 26,891      | 0.38% | $5.85 |
        | Adname6-1-12-2023   | 30,217      | 0.39% | $4.62 |
        | Adname7-2-02-2023   | 46,782      | 0.76% | $2.95 |
        | Adname8-3-17-2023   | 95,612      | 0.81% | $2.57 |
        | Adname9-2-13-2023   | 159,435     | 0.73% | $3.32 |
        '''

    elif 'Q2 goals' in query:
        model_response = '''
        Based on the performance report for the quarter, here are some objectives for Loreal-Singapore in the upcoming quarter:

        1. Enhance brand awareness by 8% among the target audience through strategic social media ad campaigns and impactful collaborations with beauty influencers by the end of the quarter.
        2. Drive a 10% increase in website traffic through well-optimized Google search campaigns and captivating display ads by the end of the quarter.
        3. Generate 500 high-quality leads by leveraging engaging email marketing campaigns and targeted paid search ads by the end of the quarter.
        4. Achieve a 10% growth in sales revenue by implementing compelling social media and email campaigns that offer exclusive promotions and incentives by the end of the quarter.
        5. Boost social media engagement by 30% through a dynamic blend of influencer partnerships, shareable content creation, and captivating social media contests by the end of the quarter.
        6. Cultivate a stellar brand reputation by accumulating 500 positive reviews across various platforms, including Facebook, Google reviews, and more, by the end of the quarter.
        7. Expand into new retail markets, increase B2B interactions by 20%, and elevate direct-to-customer marketing efforts by 20% to tap into fresh target markets by the end of the quarter.
        8. Mitigate customer churn rate by 10% through the implementation of personalized email campaigns, enticing reward programs, and comprehensive feedback surveys by the end of the quarter.
        9. Augment the company's market share by 15% by prominently featuring Loreal's unique selling propositions (USPs) in social media campaigns and paid search ads by the end of the quarter.
        10. Establish Loreal as an industry thought leader by developing 5 informative resources, including webinars, articles, and infographics, and actively sharing them across multiple platforms to generate a minimum of 1,000 downloads/views by the end of the quarter.
        '''

    elif 'save' in query:
        model_response = '''   
        The objectives for next quarter have been saved to your notes as "Q2 objectives". Is there anything else I can do for you?
        '''
    
    else:
        model_response=''
    
    return str(model_response)
